<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\BookingsAPI.Application\BookingsAPI.Application.csproj" />
    <ProjectReference Include="..\src\BookingsAPI.Domain\BookingsAPI.Domain.csproj" />
    <ProjectReference Include="..\src\BookingsAPI.Infrastructure\BookingsAPI.Infrastructure.csproj" />
    <ProjectReference Include="..\src\EventsAPI.Domain\EventsAPI.Domain.csproj" />
    <ProjectReference Include="..\src\EventsAPI.Infrastructure\EventsAPI.Infrastructure.csproj" />
    <ProjectReference Include="..\src\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
